name: ci

on:
    push:
        paths-ignore:
            - 'changelog.md'
            - 'README.md'
    pull_request:

jobs:
    build:
        runs-on: windows-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v5
              with:
                  submodules: true
                  fetch-depth: 0

            - name: Install .NET 9.0
              uses: actions/setup-dotnet@v5
              with:
                  global-json-file: global.json

            - name: Build, Test, Pack, Publish
              shell: bash
              run: |
                  dotnet tool restore
                  dotnet dotnet-releaser run --nuget-token "${{secrets.NUGET_TOKEN}}" --github-token "${{secrets.GITHUB_TOKEN}}" dotnet-releaser.toml
